name: covid19
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.1
  url_launcher: ^5.4.11
  shared_preferences:
  bubble_tab_indicator: ^0.1.4
  country_list_pick: ^1.0.0+3
  pie_chart: ^4.0.1
  clay_containers: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/
